---
title: "p8105_hw5_rh2916"
author: "Rui Huang"
date: "November 1, 2018"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(purrr)
```

### Start with a dataframe containing all file names
```{r}
df = as.data.frame(list.files(path = "./data"))
colnames(df) = "filename"
```

### Iterate over file names and tidy the result

```{r, message=FALSE}
read_data = function(subject) {
  
  read_csv(paste0("./data/",subject))%>%
    janitor::clean_names() 
}

output = map_df(df[ ,1], read_data)

id = c(1:20)

df_problem1 = cbind(df, id, output) %>%
  mutate(filename = str_replace(filename, ".csv", ""))%>%
  separate(filename, into = c("control_arm", "subject_id"), sep = "_") %>%
  gather(key = week, value = observations, week_1:week_8) %>% 
  mutate(week = as.numeric(str_replace(week, "week_", "")),
         id = as.factor(id))
```

### Make a spaghetti plot

```{r}
df_problem1 %>%
  ggplot(aes(x = week, y = observations, color = id)) +
  geom_line() +
  facet_grid(~control_arm) +
  theme(legend.position = "bottom")+
  labs(
    x = "week",
    y = "value"
  )+
  ggtitle("Observations on each subject over time")
```






